"""Add user name

Revision ID: 09171f4469e5
Revises: 7191382860e6
Create Date: 2025-01-27 12:14:45.042071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09171f4469e5'
down_revision = '7191382860e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
