"""Add sharing capabilities to Goal and Task models

Revision ID: 161185828ab7
Revises: ad8670806e85
Create Date: 2025-01-27 14:29:17.680581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161185828ab7'
down_revision = 'ad8670806e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('permission_level', sa.String(length=20), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('permission_level', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('permission_level')
        batch_op.drop_column('shared_with')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('permission_level')
        batch_op.drop_column('shared_with')

    op.drop_table('comment')
    # ### end Alembic commands ###
