"""Add log table

Revision ID: 48004a3ad2b7
Revises: e01c1bdda488
Create Date: 2025-01-22 10:51:20.153867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48004a3ad2b7'
down_revision = 'e01c1bdda488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
