"""Add reminder fields to Task and Goal models

Revision ID: 5764acceed04
Revises: 9ee5c289cb17
Create Date: 2025-01-23 18:29:27.124414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5764acceed04'
down_revision = '9ee5c289cb17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notified', sa.Boolean(), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('notified')
        batch_op.drop_column('reminder_time')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('notified')
        batch_op.drop_column('reminder_time')

    # ### end Alembic commands ###
